#!/bin/sh

case "$1" in
start)
    echo "starts aesdsocket in daemon mode"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    ;;
stop)
    echo "stops aesdsocket in daemon mode"
    start-stop-daemon -K -n aesdsocket
    ;;
*)
    echo "Usage: $0 <start|stop>"
    exit 1
    ;;
esac